name = "acme-index-workers"
main = "src/index.ts"
compatibility_date = "2023-05-23"
compatibility_flags = [ "nodejs_compat" ]

# KV Namespace binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/kv
[[kv_namespaces]]
binding = "TEXTBOOK"
id = "8fa37e6eea3c4942a9d0bd595edc261d"
preview_id = "97caa1d396fd413a84900e581cb02f0d"

[[kv_namespaces]]
binding = "USER_DATA"
id = "fe02d788be204cbd831ec10fe8c6c231"
preview_id = "04216792aadc4337b5c671d76ccef2a8"

[[r2_buckets]]
binding = 'DOCUMENT_MEDIA'
bucket_name = 'document-media'
preview_bucket_name = 'document-media-preview'

# # Durable Object binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/durable-objects
# [[durable_objects]]
# binding = "MY_DURABLE_OBJECT"
# class_name = "MyDurableObject"

# # Bucket binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/kv#bucket
# [[buckets]]
# binding = "MY_BUCKET"
# name = "my-bucket"
# bucket_id = "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"

# # Service binding - For more information: https://developers.cloudflare.com/workers/platform/services
# [[routes]]
# binding = "MY_SERVICE"
# pattern = "/api/*"
# script = "api.js"

# # Queue binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/queues
# [[queues]]
# binding = "MY_QUEUE"
# name = "my-queue"
# zone_id = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"

# [env.production]
# MY_VARIABLE = "production_value"

# [env.staging]
# MY_VARIABLE = "staging_value"

# [env.shared]
# SHARED_VARIABLE = "shared_value"
